export type KitEditorType = {
        tool: string;
        card: string;
        width: number;
        setWidth: (n: number) => void;
        height: number;
        setHeight: (n: number) => void;
        corner?: number;
        setCorner?: (n: number) => void;
        opacity?: number;
        setOpacity?: (n: number) => void;
        border?: { c: string; n: number };
        setBorderWidth?: (n) => void;
        setBorderColor: (c) => void;
        glass?: boolean;
        setGlass?: (b: boolean) => void;
        shadow?: boolean;
        setShadow?: (b: boolean) => void;
        xyz?: { x: number; y: number; z: number };
        setX?: (n: number) => void;
        setY?: (n: number) => void;
        setZ?: (n: number) => void;
};
